name: AbsenPKL

on:
  schedule:
    - cron: '45 0 * * *'  # 07:45 WIB
  workflow_dispatch:

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Jalankan script absen.sh (bagas)
        run: |
          chmod +x absen.sh
          ./absen.sh


      - name: Jalankan script absen2.sh (agung)
        run: |
          chmod +x absen2.sh
          ./absen2.sh
