name: Auto Absen PKL

on:
  schedule:
    - cron: '45 0 * * *'  # 00:45 UTC = 07:45 WIB
  workflow_dispatch:

jobs:
  absen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Jalankan script absen
        run: python main.py
