name: Absen PKL Pagi

# +-------------------------------------------+
# |          GitHub Actions Cron Job          |
# |                                           |
# |    Schedule: 0 0 * * * (Every midnight)   |
# |                                           |
# |       ┌───────────── Minute (0 - 59)      |
# |       │ ┌───────────── Hour (0 - 23)      |
# |       │ │ ┌───────────── Day of month     |
# |       │ │ │ ┌───────────── Month (1-12)   |
# |       │ │ │ │ ┌───────────── Day of week  |
# |       │ │ │ │ │                           |
# |       │ │ │ │ │                           |
# |       0 0 * * *                           |
# +-------------------------------------------+

on:
  schedule:
    # Example cron expressions:
    # - '0 0 * * *'   # Run every day at midnight UTC
    # - '15 3 * * *'  # Run every day at 3:15 AM UTC
    # - '0 */6 * * *' # Run every 6 hours
    - cron: '45 0 * * *'  # Run every day at midnight UTC

jobs:
  cron_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add your job steps here
      - name: Absen 1
        run: |
          echo "Running absen 1"
          # Add your actual cron job commands here
          chmod +x absen.sh
          ./absen.sh

      - name: Absen 2
        run: |
          echo "Running absen 2"
          # Add your actual cron job commands here
          chmod +x absen2.sh
          ./absen2.sh
